export {
  createUniversityDiplomaClaimCommitments,
  createUniversityDiplomaFixture,
  createUniversityDiplomaProductionClaimOpenings,
  createUniversityDiplomaProductionClaimProfile,
  createUniversityDiplomaProductionCredentialFixture,
  createUniversityDiplomaProductionPresentationFixture,
  createUniversityDiplomaProductionPublicClaims,
  padText,
  UNIVERSITY_DIPLOMA_DIRECT_CLAIM_FIELDS,
  UNIVERSITY_DIPLOMA_PRIVACY_BOUNDARY,
  UNIVERSITY_DIPLOMA_PRODUCTION_COMMITMENT_CANDIDATES,
  UNIVERSITY_DIPLOMA_PRODUCTION_COMMITMENT_FIELDS,
  UNIVERSITY_DIPLOMA_PRODUCTION_PROFILE,
  UNIVERSITY_DIPLOMA_PRODUCTION_PUBLIC_CLAIM_FIELDS,
  type UniversityDiplomaDirectClaimField,
  type UniversityDiplomaDisclosureOptions,
  type UniversityDiplomaFixture,
  type UniversityDiplomaPrivacyBoundary,
  type UniversityDiplomaProductionClaimOpenings,
  type UniversityDiplomaProductionClaimProfile,
  type UniversityDiplomaProductionCommitmentCandidate,
  type UniversityDiplomaProductionCommitmentField,
  type UniversityDiplomaProductionCredentialFixture,
  type UniversityDiplomaProductionPresentationFixture,
  type UniversityDiplomaProductionProfile,
  type UniversityDiplomaProductionPublicClaimField,
  type UniversityDiplomaRequestOptions,
  type UniversityDiplomaSignerOptions,
} from "./testing/credential-fixtures.js";
