export { assertAggregateDecisionProfileV1 } from "./aggregate-decision-validation.js";
export { resolveCredentialComposition } from "./composition-resolver.js";
export type {
  AggregateDecisionProfileV1,
  CapabilityProviderCatalogV1,
  CapabilityProviderDescriptor,
  CircuitRequirement,
  CompactEntrypointRequirement,
  ConcreteArtifactIdentity,
  ConcreteDeploymentIdentity,
  ConformanceFixtureReference,
  CredentialDeploymentAssemblyV1,
  CredentialDeploymentComponents,
  CredentialDeploymentRole,
  CredentialFamilyProfileV1,
  CredentialFamilyReference,
  CredentialPackageDomain,
  CredentialProfileDenyRule,
  CredentialProfileMaturity,
  CredentialProfileRequirementsV1,
  CredentialProtocolProfile,
  CredentialSemanticAxesV1,
  CredentialStatusProfile,
  DeploymentComponentSelection,
  DidEvidenceProfile,
  DisabledDeploymentComponent,
  DisabledStatusProfile,
  EnabledStatusProfile,
  ExactCredentialPackageRequirement,
  HolderBindingMode,
  HolderBindingProfile,
  IssuanceProfile,
  MaturityAssessmentReference,
  PresentationProfile,
  PrivateVerificationInputSource,
  ProfileClaimSemantics,
  ProtectedMutationProfile,
  ProviderRequirement,
  ResolveCredentialCompositionInput,
  ResolvedArtifactRequirement,
  ResolvedCredentialCompositionV1,
  ResolvedProviderIdentity,
  SelectedDeploymentComponent,
  TrustedTimeProfile,
  TrustEvidenceProfile,
  VerificationProfile,
  VerificationProfileId,
  VersionedCapabilityReference,
} from "./composition-types.js";
export {
  assertCapabilityProviderCatalogV1,
  assertCredentialDeploymentAssemblyV1,
  assertCredentialFamilyProfileV1,
  CREDENTIAL_DEPLOYMENT_ROLES,
  CREDENTIAL_PROFILE_DENY_RULES,
} from "./composition-validation.js";
export {
  CredentialModelError,
  type CredentialModelErrorCode,
} from "./errors.js";
export { resolveRuntimeCredentialFamily } from "./runtime-family-resolver.js";
export type {
  ResolvedRuntimeCredentialFamily,
  ResolveRuntimeCredentialFamilyInput,
  RuntimeCredentialFamilyArtifactIdentity,
  RuntimeCredentialFamilyAuthenticatedMetadataV1,
  RuntimeCredentialFamilyAuthenticationEvidence,
  RuntimeCredentialFamilyPackageIdentity,
  RuntimeCredentialFamilyPublicSurfaceV1,
  RuntimeCredentialFamilyRecordV1,
  RuntimeCredentialFamilyRegistryV1,
  RuntimeCredentialFamilyResolution,
  RuntimeCredentialFamilyTrustDecision,
  RuntimeCredentialFamilyTrustVerifier,
  RuntimeCredentialFamilyUnsupported,
  RuntimeCredentialFamilyUnsupportedCode,
} from "./runtime-family-types.js";
export type {
  ClaimDisclosure,
  CredentialCapabilityDescriptor,
  CredentialCapabilityKind,
  CredentialClaimDescriptor,
  CredentialCodec,
  CredentialCompositionManifest,
  CredentialFamilyDefinition,
  CredentialPackageRequirement,
  CredentialSchemaDescriptor,
  PresentationCodec,
  ProofArtifactRequirement,
} from "./types.js";
export {
  assertCredentialCompositionManifest,
  assertCredentialFamilyDefinition,
  defineCredentialFamily,
} from "./validation.js";
