{
  lib,
  stdenvNoCC,
  nodejs_24,
  pnpm_10,
  fetchPnpmDeps,
  pnpmConfigHook,
  compact-toolchain,
  compact-midnight,
  midnight-circuit-params,
  src,
}:

stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "midnight-vc-npm-artifacts";
  version = "0.2.0";

  inherit src;

  # Use pnpm_10 explicitly — the lockfile is v9 (generated by pnpm 10).
  # nixpkgs' default pnpm (pnpmLatest) may be a different major version
  # (e.g. pnpm 11) which is incompatible with lockfile v9 and causes
  # ERR_PNPM_LOCKFILE_CONFIG_MISMATCH on overrides validation.
  pnpmDeps = fetchPnpmDeps {
    inherit (finalAttrs) pname version;
    inherit src;
    pnpm = pnpm_10;
    hash = "sha256-hcgRAuYQ2IjLsqvRj8uRAYKkHNy34nhFvI6aNEB3f3k=";
    fetcherVersion = 3;
  };

  nativeBuildInputs = [
    compact-midnight
    compact-toolchain
    nodejs_24
    pnpm_10
    pnpmConfigHook
  ];

  buildPhase = ''
    runHook preBuild

    export PATH=${pnpm_10}/bin:$PATH
    export NPM_CONFIG_MANAGE_PACKAGE_MANAGER_VERSIONS=false
    export COMPACT_DIRECTORY=${compact-toolchain}
    export HOME=$TMPDIR

    # Pre-populate zkir circuit parameters (required for compact compile in offline sandbox)
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    pnpm run build:all

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    export PATH=${pnpm_10}/bin:$PATH
    export NPM_CONFIG_MANAGE_PACKAGE_MANAGER_VERSIONS=false
    # Pre-populate circuit parameters again for package prepack Compact compilation.
    export HOME=$TMPDIR
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    export COMPACT_DIRECTORY=${compact-toolchain}

    # Patch pack-artifacts.sh: replace git rev-parse with PWD (no .git in sandbox)
    substituteInPlace tooling/scripts/pack-artifacts.sh \
      --replace-fail 'ROOT_DIR="$(git rev-parse --show-toplevel)"' 'ROOT_DIR="$PWD"'

    mkdir -p $out
    # Consumer fixtures need registry-only dev tools; CI runs them outside the
    # network-isolated Nix build after validating the same tarball contract.
    bash tooling/scripts/pack-artifacts.sh "$out" --skip-consumer-tests

    runHook postInstall
  '';

  meta = with lib; {
    description = "Midnight verifiable credentials npm artifact tarballs";
    homepage = "https://github.com/midnight-ntwrk/midnight-verifiable-credentials";
    license = lib.licenses.asl20;
    platforms = compact-toolchain.meta.platforms;
  };
})
