{
  lib,
  stdenvNoCC,
  nodejs_24,
  pnpm_10,
  fetchPnpmDeps,
  pnpmConfigHook,
  runCommand,
  python3,
  compact-toolchain,
  compact-midnight,
  midnight-circuit-params,
  src,
}:

let
  # Strip the packageManager field from package.json so that pnpm does not
  # try to switch to a specific version during the sandbox build.  The Nix
  # derivation already pins pnpm_10 via nativeBuildInputs; the
  # packageManager field is only useful for Corepack-based workflows
  # outside the sandbox.
  patchedSrc =
    runCommand "vc-patched-src"
      {
        inherit src;
        nativeBuildInputs = [ python3 ];
      }
      ''
        cp -r $src $out
        chmod -R u+w $out

        python3 -c "import json,os; d=json.load(open('$out/package.json')); d.pop('packageManager',None); json.dump(d,open('$out/package.json','w'),indent=2)"
      '';

in
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "midnight-vc-npm-artifacts";
  version = "0.1.0";

  src = patchedSrc;

  # Use pnpm_10 explicitly — the lockfile is v9 (generated by pnpm 10).
  # nixpkgs' default pnpm (pnpmLatest) may be a different major version
  # (e.g. pnpm 11) which is incompatible with lockfile v9 and causes
  # ERR_PNPM_LOCKFILE_CONFIG_MISMATCH on overrides validation.
  pnpmDeps = fetchPnpmDeps {
    inherit (finalAttrs) pname version;
    src = patchedSrc;
    pnpm = pnpm_10;
    hash = "sha256-dbv7Ixn6Fd3ywfvSXQ7KekOT37RVySVOfoEHhRUjink=";
    fetcherVersion = 3;
  };

  nativeBuildInputs = [
    compact-midnight
    compact-toolchain
    nodejs_24
    pnpm_10
    pnpmConfigHook
  ];

  buildPhase = ''
    runHook preBuild

    export COMPACT_DIRECTORY=${compact-toolchain}
    export HOME=$TMPDIR

    # Pre-populate zkir circuit parameters (required for compact compile in offline sandbox)
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    # Run the Compact alias setup from the root postinstall contract.
    node ./tooling/scripts/ensure-compact-package-aliases.mjs

    pnpm run build:all

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    # Pre-populate circuit parameters again for package prepack Compact compilation.
    export HOME=$TMPDIR
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    export COMPACT_DIRECTORY=${compact-toolchain}

    # Patch pack-artifacts.sh: replace git rev-parse with PWD (no .git in sandbox)
    substituteInPlace tooling/scripts/pack-artifacts.sh \
      --replace-fail 'ROOT_DIR="$(git rev-parse --show-toplevel)"' 'ROOT_DIR="$PWD"'

    mkdir -p $out
    bash tooling/scripts/pack-artifacts.sh "$out"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Midnight verifiable credentials npm artifact tarballs";
    homepage = "https://github.com/midnight-ntwrk/midnight-verifiable-credentials";
    license = lib.licenses.asl20;
    platforms = compact-toolchain.meta.platforms;
  };
})
