{
  lib,
  stdenvNoCC,
  nodejs_24,
  pnpm_10,
  fetchPnpmDeps,
  pnpmConfigHook,
  runCommand,
  python3,
  midnight-did-npm-artifacts,
  compact-toolchain,
  compact-midnight,
  midnight-circuit-params,
  src,
}:

let
  # The 5 midnight-did .tgz files that must come from the flake input.
  # midnight-did-secret-storage is NOT among these — it stays from the
  # committed source tree because it is not a midnight-did artifact workspace.
  vendorPackagesFromFlake = [
    "midnight-did"
    "midnight-did-api"
    "midnight-did-contract"
    "midnight-did-domain"
    "midnight-did-jubjub-schnorr"
  ];

  # Map from vendor package short name to lockfile v3 path
  vendorLockfilePaths = {
    "midnight-did"              = "node_modules/@midnight-ntwrk/midnight-did";
    "midnight-did-api"          = "node_modules/@midnight-ntwrk/midnight-did-api";
    "midnight-did-contract"     = "node_modules/@midnight-ntwrk/midnight-did-contract";
    "midnight-did-domain"       = "node_modules/@midnight-ntwrk/midnight-did-domain";
    "midnight-did-jubjub-schnorr" = "node_modules/@midnight-ntwrk/midnight-did-jubjub-schnorr";
    "midnight-did-secret-storage" = "node_modules/@midnight-ntwrk/midnight-did-secret-storage";
  };

  # Replace the 5 committed vendor .tgz files with those from midnight-did's
  # npm-artifacts flake output and patch pnpm-lock.yaml with the replacement
  # tarball integrity hashes.
  patchedSrc = runCommand "vc-patched-src" {
    inherit src;
    nativeBuildInputs = [ python3 ];
  } ''
    cp -r $src $out
    chmod -R u+w $out

    # Replace 5 vendor .tgz files with those from midnight-did npm-artifacts
    for pkg in ${lib.concatStringsSep " " vendorPackagesFromFlake}; do
      tgzName="midnight-ntwrk-''${pkg}-0.1.0.tgz"
      ln -sf ${midnight-did-npm-artifacts}/$tgzName \
        $out/tooling/vendor/midnight-did/$tgzName
    done

    # Strip the packageManager field from package.json so that pnpm does not
    # try to switch to a specific version during the sandbox build.  The Nix
    # derivation already pins pnpm_10 via nativeBuildInputs; the
    # packageManager field is only useful for Corepack-based workflows
    # outside the sandbox.
    python3 -c "import json,os; d=json.load(open('$out/package.json')); d.pop('packageManager',None); json.dump(d,open('$out/package.json','w'),indent=2)"

    # Patch pnpm-lock.yaml:
    python3 <<'PYEOF'
    import base64, hashlib, os, re

    out = os.environ["out"]

    lockfile_path = os.path.join(out, "pnpm-lock.yaml")
    with open(lockfile_path) as f:
        lockfile = f.read()

    vendor_dir = os.path.join(out, "tooling", "vendor", "midnight-did")
    flake_pkgs = set(${builtins.toJSON vendorPackagesFromFlake})

    for pkg_short in flake_pkgs:
        tgz_name = f"midnight-ntwrk-{pkg_short}-0.1.0.tgz"
        tgz_path = os.path.realpath(os.path.join(vendor_dir, tgz_name))

        with open(tgz_path, "rb") as f:
            content = f.read()

        integrity_hash = hashlib.sha512(content).digest()
        integrity = "sha512-" + base64.b64encode(integrity_hash).decode()

        escaped_tgz = re.escape(tgz_name)
        pattern = (
            r"(resolution: \{integrity: )sha512-[^,}]+"
            r"(, tarball: file:tooling/vendor/midnight-did/" + escaped_tgz + r"\})"
        )
        lockfile, count = re.subn(pattern, r"\1" + integrity + r"\2", lockfile)
        if count != 1:
            raise RuntimeError(f"Expected one pnpm lockfile integrity for {tgz_name}, found {count}")
        print(f"Updated integrity for {pkg_short}: {integrity[:30]}...")

    with open(lockfile_path, "w") as f:
        f.write(lockfile)
    PYEOF
  '';

in
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "midnight-vc-npm-artifacts";
  version = "0.1.0";

  src = patchedSrc;

  # Use pnpm_10 explicitly — the lockfile is v9 (generated by pnpm 10).
  # nixpkgs' default pnpm (pnpmLatest) may be a different major version
  # (e.g. pnpm 11) which is incompatible with lockfile v9 and causes
  # ERR_PNPM_LOCKFILE_CONFIG_MISMATCH on overrides validation.
  pnpmDeps = fetchPnpmDeps {
    inherit (finalAttrs) pname version;
    src = patchedSrc;
    pnpm = pnpm_10;
    hash = "sha256-rr2bPydOI+CMQv3pIdArDLSHcEBkq1oQrYLTdjqd0Mk=";
    fetcherVersion = 3;
  };

  nativeBuildInputs = [
    compact-midnight
    compact-toolchain
    nodejs_24
    pnpm_10
    pnpmConfigHook
  ];

  buildPhase = ''
    runHook preBuild

    export COMPACT_DIRECTORY=${compact-toolchain}
    export HOME=$TMPDIR

    # Pre-populate zkir circuit parameters (required for compact compile in offline sandbox)
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    # Run postinstall scripts that were stripped from package.json
    # (ensure-midnight-did-api-paths is NOT run here: the flake-built .tgz
    # restructures config.js to re-export from package-paths.js, so patching
    # package-paths.js via substituteInPlace below is sufficient.)
    node ./tooling/scripts/ensure-compact-package-aliases.mjs

    # Patch midnight-did-api contract path: the flake-built .tgz uses package-paths.js
    # for the contract path config. config.js re-exports from package-paths.js, so
    # patching package-paths.js is sufficient.
    # The ensure-midnight-did-api-paths.mjs script cannot be used here — it expects
    # the path string to be inline in config.js, but the flake-built layout
    # moved it to package-paths.js, causing the script to throw.
    #
    # pnpm installs @midnight-ntwrk/midnight-did-api into the .pnpm store
    # (it is an override, not a direct root dependency), so its node_modules
    # entry lives under node_modules/.pnpm/… rather than at the flat
    # node_modules/@midnight-ntwrk/midnight-did-api/ path.  Use find to
    # locate the real file.
    API_PKG_PATHS_JS=$(find node_modules/.pnpm -path "*+midnight-did-api@*/dist/package-paths.js" | head -1)
    if [ -z "$API_PKG_PATHS_JS" ]; then
      echo "ERROR: could not find midnight-did-api/dist/package-paths.js in pnpm store"
      exit 1
    fi
    substituteInPlace "$API_PKG_PATHS_JS" \
      --replace-fail '"contract", "src", "managed", "did"' '"midnight-did-contract", "dist", "managed", "did"'

    # Build all 14 workspaces in dependency layer order.
    # No turbo — its caching and parallel scheduling provide zero value in a
    # clean Nix sandbox. Explicit ordering is simpler, more auditable, and
    # consistent with the pack-artifacts.sh pattern.

    ## Layer 1: core primitives (no vc-internal deps)
    pnpm --dir packages/core/primitives/credentials run build

    ## Layer 2: depend on credentials
    pnpm --dir packages/registry/status-registry run build
    pnpm --dir packages/core/capabilities/same-holder run build
    pnpm --dir packages/core/primitives/iso-registry run build

    ## Layer 3: pure TypeScript (no compact compile)
    pnpm --dir packages/components/adapters/offchain-did run build
    pnpm --dir packages/protocols/openid run build

    ## Layer 4: credential families (depend on layers 1-3)
    pnpm --dir packages/prototypes/credential-families/birth run build
    pnpm --dir packages/prototypes/credential-families/birth-secret run build
    pnpm --dir packages/prototypes/credential-families/hello-family run build
    pnpm --dir packages/prototypes/credential-families/dummy-claims run build
    pnpm --dir packages/prototypes/credential-families/mixed-claims run build
    pnpm --dir packages/prototypes/credential-families/university-diploma run build
    pnpm --dir packages/prototypes/credential-families/digital-passport run build

    ## Layer 5: orchestration (depends on birth + age-gate contracts)
    pnpm --dir packages/components/orchestration/protocol run build

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    # Pre-populate circuit parameters again for digital-passport's prepack → compact compile
    export HOME=$TMPDIR
    mkdir -p $HOME/.cache/midnight/zk-params
    cp -r ${midnight-circuit-params}/* $HOME/.cache/midnight/zk-params/

    export COMPACT_DIRECTORY=${compact-toolchain}

    # Patch pack-artifacts.sh: replace git rev-parse with PWD (no .git in sandbox)
    substituteInPlace tooling/scripts/pack-artifacts.sh \
      --replace-fail 'ROOT_DIR="$(git rev-parse --show-toplevel)"' 'ROOT_DIR="$PWD"'

    mkdir -p $out
    bash tooling/scripts/pack-artifacts.sh "$out"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Midnight verifiable credentials npm artifact tarballs";
    homepage = "https://github.com/midnight-ntwrk/midnight-verifiable-credentials";
    license = lib.licenses.asl20;
    platforms = compact-toolchain.meta.platforms;
  };
})
