export type { AuthorityBoundProofVerificationResultV1 } from "./authority-bound-verifier.js";
export { verifyProofWithAuthorityV1 } from "./authority-bound-verifier.js";
export type {
  AuthorityActorKeyRequirementV1,
  AuthorityActorRoleV1,
  AuthorityEvidenceCompositionV1,
  AuthorityEvidencePolicyV1,
  AuthorityEvidenceProfileV1,
  AuthorityEvidenceProviderPolicyV1,
  AuthorityEvidenceReasonCodeV1,
  AuthorityEvidenceVerificationResultV1,
  AuthorityResolvedProviderIdentityV1,
  AuthorityVerificationContextV1,
  CanonicalAuthorityActorTranscriptV1,
  CanonicalAuthorityVerificationTranscriptV1,
  CanonicalDidEvidenceSelectionV1,
  CanonicalTrustEvidenceSelectionV1,
  DidMethodEvidenceProviderV1,
  DidMethodEvidenceRequestV1,
  DidMethodEvidenceV1,
  DidMethodLifecycleStatusV1,
  ScopedAuthorityEvidenceReasonCodeV1,
  TrustAuthorizationEvidenceProviderV1,
  TrustAuthorizationEvidenceRequestV1,
  TrustAuthorizationEvidenceV1,
} from "./authority-evidence.js";
export {
  AUTHORITY_ACTOR_ROLES_V1,
  createAuthorityEvidencePolicyV1,
  verifyAuthorityEvidenceV1,
} from "./authority-evidence.js";
export { CredentialProofsError, type CredentialProofsErrorCode } from "./errors.js";
export {
  assertArtifactBytes,
  base64UrlDecode,
  base64UrlEncode,
  CANONICALIZATION_PROFILE,
  canonicalize,
  computeBuildManifestDigest,
  computeDeploymentManifestDigest,
  computeManifestDigest,
  computeProofManifestDigest,
  computeSha256Digest,
  isEd25519Signature,
  isSha256Digest,
  MANIFEST_SIGNATURE_ALGORITHM,
  serializeBuildManifest,
  serializeCanonicalJson,
  serializeDeploymentManifest,
  serializeProofManifest,
} from "./serialization.js";
export {
  assertBuildManifestIntegrity,
  assertDeploymentManifestIntegrity,
  createBuildManifest,
  createDeploymentManifest,
  createDeploymentManifestSignature,
  createProofManifest,
  type DeploymentManifestVerificationOptions,
  generateManifestSigningKeyPair,
  type ManifestSigningKey,
  resolveArtifactBytes,
  resolveVerifiedArtifact,
  verifyBuildManifestDigest,
  verifyDeploymentManifest,
} from "./signatures.js";
export type {
  TrustedTimeAnchorV1,
  TrustedTimeAnchorVerificationV1,
  TrustedTimeAnchorVerifierV1,
  TrustedTimeAttestationSignatureV1,
  TrustedTimeAttestationSignatureVerifierV1,
  TrustedTimeAuthorityEvidenceV1,
  TrustedTimeAuthorityVerifierV1,
  TrustedTimeCheckpointV1,
  TrustedTimeEvidenceV1,
  TrustedTimeModeV1,
  TrustedTimePolicyV1,
  TrustedTimeProfileV1,
  TrustedTimeReasonCodeV1,
  TrustedTimeScopeV1,
  TrustedTimeSequenceKeyV1,
  TrustedTimeStatementV1,
  TrustedTimeVerificationResultV1,
} from "./trusted-time.js";
export {
  computeTrustedTimeAnchorDigestV1,
  computeTrustedTimeAuthorityPolicyDigestV1,
  computeTrustedTimeEvidenceDigestV1,
  computeTrustedTimeScopeDigestV1,
  computeTrustedTimeSequenceKeyDigestV1,
  computeTrustedTimeStatementDigestV1,
  createTrustedTimeAuthorityVerifierV1,
  verifyTrustedTimeEvidenceV1,
} from "./trusted-time.js";
export type {
  ArtifactResolver,
  BuildManifest,
  DeploymentManifest,
  DeploymentManifestSignature,
  DeploymentReference,
  DeploymentSupportWindow,
  ManifestKeyResolver,
  ManifestSignatureAlgorithm,
  ProofArtifactDescriptor,
  ProofArtifactRole,
  ProofBuildManifest,
  ProofBuildToolchain,
  ProofBytes,
  ProofCircuitDescriptor,
  ProofDeploymentManifest,
  ProofFamily,
  ProofJob,
  ProofManifest,
  ProofProvider,
  ProofResult,
  ProofVerificationResult,
  ProofVerifier,
  ResolvedProofArtifact,
  Sha256Digest,
} from "./types.js";
export {
  assertBuildManifest,
  assertDeploymentManifest,
  assertProofJob,
  assertProofManifest,
  assertProofResult,
  assertProofVerificationResult,
  defineBuildManifest,
  defineDeploymentManifest,
  defineProofJob,
  defineProofManifest,
  validateBuildManifest,
  validateDeploymentManifest,
  validateProofJob,
  validateProofManifest,
  validateProofResult,
  validateProofVerificationResult,
} from "./validation.js";
